tap "eth-p/software"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bat"
brew "docker"
brew "exa"
brew "fileicon"
brew "gh"
brew "httpie"
brew "jenv"
brew "less"
brew "mackup"
brew "mas"
brew "node"
brew "wget"
brew "zsh"
brew "eth-p/software/bat-extras"
cask "1password"
cask "betterzip"
cask "beyond-compare"
cask "boxcryptor"
cask "daisydisk"
cask "dropbox"
cask "forklift"
cask "gitkraken"
cask "google-chrome"
cask "google-drive"
cask "intellij-idea"
cask "istat-menus"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "openoffice"
cask "oracle-jdk"
cask "oxygen-xml-editor"
cask "permute"
cask "pycharm-ce"
cask "skim"
cask "textsniper"
cask "visual-studio-code"
cask "whatsapp"
mas "Kindle", id: 405399194
mas "NordVPN", id: 905953485
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Peek", id: 1554235898
mas "Pixelmator Pro", id: 1289583905
mas "Xee³", id: 639764244
